### ISSUE TITLE
Deprecated Command Warning

### ISSUE THREAD

**Issue by ScottWell1** [anoved/OctoPrint-EmailNotifier#16]
Following warning is issued when OctoPrint-EmailNotifier is invoked:

> py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_emailnotifier/**init**.py:60: DeprecationWarning: globalGet has been renamed to global_get

Line 60, please change 'globalGet' to 'global_get'.

**Comment by dpcrook** [comment]
I noticed this too, while I turned on debug logging to troubleshoot `timelapse` plugin.

```
2016-10-26 20:49:41,690 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_emailnotifier/__init__.py:60: Deprecatio
nWarning: globalGet has been renamed to global_get
  snapshot_url = self._settings.globalGet(["webcam", "snapshot"])
```
