### ISSUE TITLE
No way to access Keyring if you only use Web UI

### ISSUE THREAD

**Issue by Snipercaine** [anoved/OctoPrint-EmailNotifier#17]
Maybe I'm in the minority here, but I only use the Web UI on my Octopi.  I've read the other issues here about SMTP passwords but because I only use the web UI none of the solutions will work for me.  I can't access the keyring and I can't use yagmail.  I admit I'm not a programmer so there are things in the other issue discussions I do not understand.

Is there no other way for me to use the EmailNotifier if I only use the web to access my Octopi?

**Comment by Snipercaine** [comment]
Ok. so I now know how to ssh into my "headless" octopi.  I've tried installing yagmail but I still can't get my email and password into the keyring to be used by the EmailNotifier.  Would someone please make a short "how-to" on this for us non-programmers?  Please.

**Comment by weeheavy** [comment]
It was not obvious to me either to be honest, at first I didn't realize `yagmail` was a Python package. But here's a short explanation:

- SSH into your OctoPrint instance with the user running OctoPrint. With OctoPi, username is "pi" (see https://octopi.octoprint.org for the default password)
- Load virtualenv: `source ~/oprint/bin/activate`
- Install required packages: `pip install keyrings.alt yagmail`
- Register your account: `~/oprint/bin/python -c "import yagmail; yagmail.register('myusername', 'mypassword')"` (note: some e-mail providers require the full e-mail address, some don't)
- Return to OctoPrint Web UI, navigate to "Settings", "Email Notifier" and fill-out the settings. Make sure that the value for "Username" matches the "myusername" value specified in the command above.

**Comment by Snipercaine** [comment]
Thanks. That did the trick.
