### ISSUE TITLE
Specify MIME Type of webcam snapshots int the email

### ISSUE THREAD

**Issue by oxivanisher** [anoved/OctoPrint-EmailNotifier#18]
#### What were you doing?

Receiving webcam pictures emails from the OctoPrint-EmailNotifier
#### What did you expect to happen?

To be able to open the image in K-9 (Android mail client)
#### What happened instead?

I have to download it first, and can only open it then. This is probably happening also in other email clients.
#### Branch & Commit or Version of OctoPrint

all AFAIK
#### Printer model & used firmware incl. version

Not important, but Kossel XL 800
#### Browser and Version of Browser, Operating System running Browser

Android 6, K-9 Mail (will happen in other situations also)
#### Screenshot(s) showing the problem:

![octoptint_bug](https://cloud.githubusercontent.com/assets/264994/16260278/fc935854-3866-11e6-9d1d-a8e466fcc500.png)

**Comment by oxivanisher** [comment]
The file itself has the correct MIME type:
`$ file --mime-type Downloads/snapshot.jpg 
Downloads/snapshot.jpg: image/jpeg
`

**Comment by anoved** [comment]
Thanks for the report. Yeah, this is a known issue. https://github.com/anoved/OctoPrint-EmailNotifier/issues/5

Frankly the intricacies of email formatting (and making the web UI more sophisticated) are a bit outside my area of expertise/interest, so any outside help patching this plugin to be more user friendly is welcome as I am unlikely to find the time to prioritize it myself.
