### ISSUE TITLE
Problem with plugin installation

### ISSUE THREAD

**Issue by JanSykor** [anoved/OctoPrint-EmailNotifier#20]
Hello
I have problem with installation of this plugin. During installation I received next error.
There is no matter if installation starting from Octoprint or over SSH.
I think that problem is some rights adjustment, but I can´t find what is wrong.

`Instalace pluginu "Email Notifier" z https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip...
/home/pi/OctoPrint/venv/bin/pip install https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip
Collecting https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip
Downloading https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): OctoPrint in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.2.16-py2.7.egg (from OctoPrint-EmailNotifier==0.1.1)
Collecting yagmail (from OctoPrint-EmailNotifier==0.1.1)
Downloading yagmail-0.5.148-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): flask<0.11,>=0.9 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): werkzeug<0.9,>=0.8.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): tornado<4.1,>=4.0.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): sockjs-tornado<1.1,>=1.0.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/sockjs_tornado-1.0.3-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML<3.11,>=3.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/PyYAML-3.10-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login<0.3,>=0.2.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Flask_Login-0.2.11-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Principal<0.4,>=0.3.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Babel<0.10,>=0.9 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Assets<0.11,>=0.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): markdown<2.7,>=2.6.4 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Markdown-2.6.7-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): pyserial<2.8,>=2.7 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): netaddr<0.8,>=0.7.17 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/netaddr-0.7.18-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): watchdog<0.9,>=0.8.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): sarge<0.2,>=0.1.4 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): netifaces<0.11,>=0.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/netifaces-0.10.5-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): pylru<1.1,>=1.0.9 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): rsa<3.3,>=3.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/rsa-3.2.3-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): pkginfo<1.3,>=1.2.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): requests<2.8,>=2.7.0 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): semantic_version<2.5,>=2.4.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): psutil<3.3,>=3.2.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/psutil-3.2.2-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): awesome-slugify<1.7,>=1.6.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): feedparser<5.3,>=5.2.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/feedparser-5.2.1-py2.7.egg (from OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Collecting keyring (from yagmail->OctoPrint-EmailNotifier==0.1.1)
Using cached keyring-10.0.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/itsdangerous-0.24-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/certifi-2016.09.26-py2.7.egg (from tornado<4.1,>=4.0.1->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl_match_hostname in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg (from tornado<4.1,>=4.0.1->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): blinker in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/blinker-1.4-py2.7.egg (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Babel-2.3.4-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): webassets>=0.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/webassets-0.12.0-py2.7.egg (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/argh-0.26.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg (from rsa<3.3,>=3.2->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): regex in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/regex-2016.09.22-py2.7-linux-armv7l.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): Unidecode<0.05,>=0.04.14 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/Unidecode-0.04.19-py2.7.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Using cached SecretStorage-2.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/MarkupSafe-0.23-py2.7-linux-armv7l.egg (from Jinja2>=2.4->flask<0.11,>=0.9->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pytz-2016.7-py2.7.egg (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-EmailNotifier==0.1.1)
Collecting cryptography (from secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Using cached cryptography-1.5.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Collecting cffi>=1.4.1 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Using cached cffi-1.8.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pycparser in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring->yagmail->OctoPrint-EmailNotifier==0.1.1)
Installing collected packages: cffi, cryptography, secretstorage, keyring, yagmail, OctoPrint-EmailNotifier
Running setup.py install for cffi: started
Running setup.py install for cffi: finished with status 'error'
Complete output from command /home/pi/OctoPrint/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZYL9tN/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MNn4jJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/OctoPrint/venv/include/site/python2.7/cffi:
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
running install
running build
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/cffi
copying cffi/lock.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/__init__.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/verifier.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/recompiler.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/api.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/ffiplatform.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/vengine_gen.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/commontypes.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/model.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/cparser.py -> build/lib.linux-armv7l-2.7/cffi
copying cffi/_cffi_include.h -> build/lib.linux-armv7l-2.7/cffi
copying cffi/parse_c_type.h -> build/lib.linux-armv7l-2.7/cffi
copying cffi/_embedding.h -> build/lib.linux-armv7l-2.7/cffi
running build_ext
building '_cffi_backend' extension
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/c
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
#include <ffi.h>
^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Command "/home/pi/OctoPrint/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZYL9tN/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MNn4jJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/OctoPrint/venv/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-ZYL9tN/cffi/
Hotovo!`

My installation is on RPi3 + Raspbian + Octoprint installed by this link:
https://github.com/foosel/OctoPrint/wiki/Setup-on-a-Raspberry-Pi-running-Raspbian

Other plugins was installed correctly.
Do you have somebody any ideas how to repair, please?

Thanks
Jan

**Comment by anoved** [comment]
Thanks for the report. I am quite behind in updating projects and will need to study the OctoPrint plugin system again before I can fix this. I'll post an update here when I do.

**Comment by anoved** [comment]
Consolidating in to issue #24. Thanks for the installation link. That may be helpful info as I use OctoPi (Raspbian + OctoPrint distributed as a prepared SD image). Perhaps OctoPi bundles some prerequisite packages that are problematic to install in ad hoc OctoPrint systems?
