### ISSUE TITLE
error while installing email notifier 

### ISSUE THREAD

**Issue by swapsan** [anoved/OctoPrint-EmailNotifier#22]
I get this error when i try and install email notifier  - 

Command "/home/pi/OctoPrint/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tnHXkv/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9eqCPh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/OctoPrint/venv/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-tnHXkv/cffi/

**Comment by anoved** [comment]
Thanks for the report. I have to back up to speed on how OctoPrint plugins work before I can fix this. I'll post an update here when I do.

**Comment by anoved** [comment]
Merging with issue #24.
