### ISSUE TITLE
Email on another event.

### ISSUE THREAD

**Issue by robingantois** [anoved/OctoPrint-EmailNotifier#25]
My endCode is:

G4 P900000 ;doing nothing for 15 min
G90 ;absolute positioning
G1 Y200 ; move Y forward to Auto RF power switch OFF

By --G4 P900000-- I have a connection timeout and octoprint disconnect the printer. So i do not get the "printdone" event. Is possible to replace the event "print done" by "Waiting"?

**Comment by anoved** [comment]
Technically, yes. Last year I started a [`multievent` branch](https://github.com/anoved/OctoPrint-EmailNotifier/tree/multievent) of this plugin that could email a notification in response to [any of these events](https://github.com/foosel/OctoPrint/wiki/Available-Events), including `Waiting`. I wasn't able to develop a presentable UI without investing too much time in it, but if you look at the code for that branch you may get an idea for how to modify the plugin to address your need.

**Comment by anoved** [comment]
(See issue #1 for considerably more detail on prior plans for handling notifications for different events.)

**Comment by anoved** [comment]
Closing to consolidate with #1. The `G4` dwell command should trigger an OctoPrint `Waiting` event. The multievent branch could in turn be configured to send an email notification in response to that event.
