### ISSUE TITLE
Usernames without "@" in them

### ISSUE THREAD

**Issue by mtowara** [anoved/OctoPrint-EmailNotifier#3]
There is a quirk in yagmail which automatically appends "@gmail.com" to the username if no domain is given. However there is a way to explicitly specify the username and an alias (which is used for the FROM header).

I created a fix, which also add a new textfield for the alias, would you be interested in a pull request?

**Comment by anoved** [comment]
Sure, please do!

**Comment by anoved** [comment]
Also, you might be interested to check out the `multievent` branch, which allows notifications for any Octoprint event to be set up in `config.yaml`. However, I couldn't figure out how to make a good settings UI. If you are interested in this plugin any help with that would be appreciated too!

Details: https://github.com/anoved/OctoPrint-EmailNotifier/issues/1

**Comment by anoved** [comment]
Closed as implemented by #4. Thanks for the patch.
