### ISSUE TITLE
Cannot get to work with gmail

### ISSUE THREAD

**Issue by spot1984** [anoved/OctoPrint-EmailNotifier#39]
I have it configured exactly as I have on another Octopi installation but when I click "_Send a test email_"  I just get this error:

**Sending failed. Reason:: send() got an unexpected keyword argument 'validate_email'**

I can send emails just fine from yagmail in python like this:
`>>> import yagmail`
`>>> s=yagmail.SMTP('mymail@gmail.com')`
`>>>s.send('destination@someplace.com','subject','body')`

It uses the same gmail account as the other printer so there is no problem with credentials, or alerts from google or anything.

I tried all kinds of stuff - credentials with and without the _gmail.com_, uninstalled and reinstalled, yagmail, keyrings.alt, many reboots.  Uninstalled and reinstalled it on the older working Octopi installation and it still works.

Could the latest yagmail validations may not like the mail format (?)  I can install an older version, is there one guaranteed to work?

I'm running Octopi on a pi zero w.  I had to do a full package and rpi upgrade to get wifi to work on the pi so it is running on the latest and greatest everything.

Halp!

**Comment by spot1984** [comment]
I just created new installation on a fresh SD card from the latest Octopi image **2016-03-18-octopi-jessie-lite-0.13.0.img** ...
- Wrote latest image to 16 GB SD card
- Plugged into Raspberry Pi 3
- Configured keyboard US, expanded filesystem, enabled SSH
- Setup network
- sudo apt-get update
- sudo apt-get dist-upgrade
- sudo apt-get install rpi-update
- sudo rpi-update
- reboot
_Instructions from https://github.com/anoved/OctoPrint-EmailNotifier do not work because yagmail and keyring not installed, instead..._
- source ~/oprint/bin/activate
- pip install yagmail
- pip install keyrings.alt
- python
- import yagmail
- yagmail.register('youraccount@gmail.com', 'yourpassword')
_Then tested with the following as before:_
- s=yagmail.SMTP('mymail@gmail.com')
- s.send('destination@someplace.com','subject','body')
_I received the email_

Then I configured Octoprint
- Updated to OctoPrint 1.3.4
- Installed EmailNotifier Plugin 0.1.1 from Plugin Manager
- Copied configuration fields from working installation
- Saved settings
- Re-enter configuration, slect Email Notifier, validate settings, click "Send a test email"

**Sending failed. Reason:: send() got an unexpected keyword argument 'validate_email'**

(-_-)

Note that this does not involve the Raspberry Pi Zero W nor did I do anything except what was necessary to use Email Notifier.

**Comment by jeffgolden** [comment]
it appears that validate_email is (no longer? -- i'm not sure) a valid argument to the send method of yagmail.SMTP.   I managed to get it working by changing:

mailer.send(to=emails, subject=subject, contents=body, validate_email=False)
to
mailer.send(to=emails, subject=subject, contents=body) 

~/oprint/lib/python2.7/site-packages/octoprint_emailnotifier/__init__.py

Hope this helps.

**Comment by spot1984** [comment]
Jeff,

That worked perfectly!  Thank you for the quick response and for the excellent plug in!

:-D

~ Scott

**Comment by jeffgolden** [comment]
Glad I could help -- but I should clear up.  I'm just a user of the plug-in like you.  I just ran into the same issue and fixed it by doing this.  But I share my thanks to the author,  @anoved.

**Comment by spot1984** [comment]
ROFL!  Thanks Jeff.  

I was so thrilled to get it working after wasting half a holiday weekend on it I didn't pay attention when I replied.
