### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by Stady234** [anoved/OctoPrint-EmailNotifier#52]
Is this a dead project?

**Comment by anoved** [comment]
Yes, as stated in the GitHub project description it is broken. As noted in reply to previous issues, I appreciate that others have invested effort in maintaining functional forks. I encourage anyone interested in this plugin to follow those projects. e.g.: https://github.com/anoved/OctoPrint-EmailNotifier/issues/45#issuecomment-344127088
