### ISSUE TITLE
SMTP Authentication Error

### ISSUE THREAD

**Issue by Nurgak** [anoved/OctoPrint-EmailNotifier#6]
When I try to test yagmail it throws an `SMTPAuthenticationError`. This is because Gmail doesn't consider it secure enough.

    yagmail.SMTP('sendingmail@gmail.com').send('receivingmail@gmail.com', 'Test', 'This is a test')

Of course one has to do `yagmail.register('sendingmail@gmail.com', 'password')` first.

To overcome that, one has to log in to sendingmail@gmail.com and go to *My Account* (upper left corner), *Sign-in & security*. At the very bottom, under *Connected apps & sites*, there's an option *Allow less secure apps*, this must be turned on for yagmail to work properly.

**Comment by anoved** [comment]
Welcome to the Wild West. :)

Good point, though. Most appropriate resolution would be to add a Setup section to the Readme with a note like yours explaining how to allow gmail to accept yagmail, agreed?

**Comment by Nurgak** [comment]
Sure, whatever helps. I thought it would save people some time because it wasn't very trivial.

**Comment by anoved** [comment]
Also discussed in the yagmail docs: https://github.com/kootenpv/yagmail#errors
