### ISSUE TITLE
Add "Send Test Email" button

### ISSUE THREAD

**Issue by nspaul** [anoved/OctoPrint-EmailNotifier#7]
It would be nice to have a "Send Test Email" on the plugin's configuration page. This would let a user confirm the settings are working before waiting for a long print job to finish.

**Comment by anoved** [comment]
This is a good idea - I just haven't gotten around to it. Plus, the UI part of programming OctoPrint plugins is the trickiest for me, mainly because I'm unfamiliar with the `.jinja2` layout template language.

**Comment by djvaporize** [comment]
Hi guys, I added this feature in my fork.  I want to refactor and cleanup some code before making a pull req.
If you can test the changes, that'd be great!
Thanks.
