### ISSUE TITLE
Attachement mirror horizontal/vertical

### ISSUE THREAD

**Issue by Shaztech** [anoved/OctoPrint-EmailNotifier#8]
My pi camera is mounted upside down.
In octoprint there's options Flip webcam horizontally and Flip webcam vertically.
But when I receive the email the image is upside down.
Can you add the option to flip it ?

Thanks

**Comment by djvaporize** [comment]
Hi, I could be wrong but I think the octoprint UI flips the image via CSS.
Can you try configuring the mjpegstreamer to flip it on stream and then switch the flip off on OctoPrint UI?
See here:
https://github.com/foosel/OctoPrint/wiki/MJPG-Streamer-configuration

Thanks.

**Comment by Shaztech** [comment]
I don't know which file to edit to enable flip mjpegstreamer.
Little help thx !

**Comment by djvaporize** [comment]
ssh into the pi and edit /boot/octopi.txt.  it is commented in there so it should be straightforward.  at the line that says: camera_raspi_options="-fps 10", you need to add -hf or -vf for horizontal or vertical flip.

if you are unsure how to do that, remotely poweroff the raspberry pi through the UI, pull the SD card and put it on your desktop computer and edit the text file that way.

**Comment by Shaztech** [comment]
Thanks it's working
